# Generated by Django 2.2.4 on 2019-12-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
